name: 'terminal'
description: 'Get terminal session for runner'
runs:
  using: "composite"
  steps:
    - run: echo ${{ github.action_path }}
      shell: cmd
    - run: dir ${{ github.action_path }}
      shell: cmd
    - run: echo 1
      shell: cmd
    - run: dir
      shell: cmd
