name: 'terminal'
description: 'Get terminal session for runner'
runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v3
    - run: echo 1
      shell: cmd
    - run: dir
      shell: cmd
    - run: npm install request node-pty express express-ws 
      shell: cmd
    - run: node index.js
      shell: cmd
